country_dict = {
    "AF": "Afghanistan",
    "AX": "Åland Islands",
    "AL": "Albania",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "BD": "Bangladesh",
    "BY": "Belarus",
    "BZ": "Belize",
    "BE": "Belgium",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BQ": "Bonaire",
    "BW": "Botswana",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BG": "Bulgaria",
    "KH": "Cambodia",
    "CA": "Canada",
    "IC": "Canary Islands",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CK": "Cook Islands",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "HR": "Croatia",
    "CW": "Curaçao",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "EE": "Estonia",
    "SZ": "Eswatini (Swaziland)",
    "FK": "Falkland Islands",
    "FO": "Faroe Islands",
    "FI": "Finland",
    "FR": "France",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GT": "Guatemala",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "LA": "Laos",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": "Macau",
    "MG": "Madagascar",
    "MY": "Malaysia",
    "MV": "Maldives",
    "MT": "Malta",
    "MQ": "Martinique",
    "MX": "Mexico",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "NP": "Nepal",
    "NL": "Netherlands",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NG": "Nigeria",
    "MK": "North Macedonia",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "PK": "Pakistan",
    "PS": "Palestine",
    "PA": "Panama",
    "PH": "Philippines",
    "PN": "Pitcairn Islands",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Réunion",
    "RO": "Romania",
    "RU": "Russia",
    "RW": "Rwanda",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and the Grenadines",
    "SM": "San Marino",
    "ST": "São Tomé and Príncipe",
    "SN": "Senegal",
    "RS": "Serbia",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SB": "Solomon Islands",
    "ZA": "South Africa",
    "KR": "South Korea",
    "GS": "South Georgia and the South Sandwich Islands",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SJ": "Svalbard",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "BS": "The Bahamas",
    "TN": "Tunisia",
    "TC": "Turks and Caicos Islands",
    "TR": "Turkey",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UM": "United States Minor Outlying Islands",
    "VI": "United States Virgin Islands",
    "UY": "Uruguay",
    "VU": "Vanuatu",
    "VN": "Vietnam"
}
